### ISSUE TITLE
FileServer doesn't serve embeded index.html from /

### ISSUE THREAD

**Issue by alex920** [gobuffalo/packr#10]
```
package main

import (
	"net/http"

	"github.com/gobuffalo/packr"
)

func main() {
	http.ListenAndServe("localhost:1234", http.FileServer(packr.NewBox("public")))
}
```
Index.html not served when is embedded. It returns error '404 page not found'.

Steps:

1. Run packr build
2. Delete folder public
3. Run builded exe
4. Open in browser http://localhost:1234
5. 404 page not found

os: Windows 7 x64

**Comment by metalmatze** [comment]
http://localhost:1234/index.html should work for you. To get what you want you can simply create a http.Handler listening on / that gets your index.html and simply writes the bytes to the ResponseWriter.
