### ISSUE TITLE
packr box index.html in subdir not directly accessible

### ISSUE THREAD

**Issue by d-rep** [gobuffalo/packr#101]
This is on `go version go1.11 darwin/amd64` and packr/latest

I had been using a packr box in a docker container without issues, then around Fri 10/26 I noticed the following warning message.  So I believe v1.13.7 was stable and then a recent change broke it.

> [DEPRECATED] github.com/gobuffalo/packr#Box.MustBytes has been deprecated.
> Use github.com/gobuffalo/packr#Box.Find instead.

There is no error returned but **calls to box are returning an empty response**.  Changing my MustBytes call to Find does not help.  

```
package main

import (
	"fmt"
	"net/http"
	"github.com/gobuffalo/packr"
)

func main() {
	boxBase := packr.NewBox("build")
	fmt.Println(boxBase.List())
	http.Handle("/", http.FileServer(boxBase))
	http.ListenAndServe(":3000", nil)
}
```
(I was using `negroni.NewStatic(box)` and getting empty responses, then stripped it down to the above.)

Something like `curl localhost:3000/dev/` returns the contents of index.html  as expected, but this is not:
```
curl -I localhost:3000/dev/index.html
HTTP/1.1 301 Moved Permanently
Location: ./
Date: ...
```
Was that behavior recently changed?  I thought index.html in a subdir used to be directly accessible.
Other resources come back:
```
curl -I localhost:3000/dev/apple-touch-icon.png
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 3511
Content-Type: image/png
...
```

**Comment by markbates** [comment]
According the Go documentation, this is normal behavior for `http.FileSystem` https://golang.org/pkg/net/http/#FileServer

```
As a special case, the returned file server redirects any request ending in "/index.html" to the same path, without the final "index.html".
```

**Comment by d-rep** [comment]
Sorry, I had misidentified the issue.  I pulled down our Docker image to retest the behavior and found that I was getting HTTP 200 but no content (rather than a 301).

The problem seems like requested asset names need to be in all caps?  

```
$ curl -v 127.0.0.1
* Rebuilt URL to: 127.0.0.1/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Last-Modified: Thu, 01 Nov 2018 14:56:48 GMT
< Date: Thu, 01 Nov 2018 14:56:48 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact

$ curl -v 127.0.0.1/INDEX.HTML
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /INDEX.HTML HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 01 Nov 2018 14:57:08 GMT
< Content-Length: 1048
< Content-Type: text/html; charset=utf-8
<
<!doctype html>
<html lang="en">
...
</html>
* Connection #0 to host 127.0.0.1 left intact
```

At any rate, the issue seems to have been fixed yesterday from https://github.com/gobuffalo/packr/issues/102  Thanks for the quick fix!
