### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by HazCod** [gobuffalo/packr#107]
Hello,

I m using packr v1.19.0 in a Docker build:
```
RUN packr build \
    -installsuffix 'static' \
    -ldflags '-w -s' \
    /src && mv mini /app
...
COPY --from=builder /app /app
```

Directory structure of my project;
```
.
|-- Dockerfile
|-- conf
|   |-- cert.pem
|   `-- key.pem
|-- dev.sh
|-- docker.compose
|-- go.mod
|-- go.sum
|-- handlers
|   |-- contacthandler.go
|   |-- homehandler.go
|   |-- panichandler.go
|   |-- pricinghandler.go
|   `-- producthandler.go
|-- language
|   |-- en.go
|   |-- lang.go
|   `-- lang_keys.go
|-- main.go
|-- models
|-- public
|   |-- assets
|   |   |-- css
|   |   |   |-- bootstrap.css
|   |   |   |-- font.css
|   |   |   `-- styles.css
|   `-- templates
|       |-- home
|       |   |-- about.tpl
|       |   |-- contact.tpl
|       |   |-- index.tpl
|       |   `-- pricing.tpl
|       |-- layouts
|       |   |-- frontend.tpl
|       |   `-- panic.tpl
|       `-- partials
|           `-- frontend
|               |-- footer.tpl
|               |-- header.tpl
|               `-- navbar.tpl
|-- system
|   |-- cache.go
|   |-- config.go
|   |-- logger
|   |   `-- logger.go
|   |-- router.go
|   `-- template.go
`-- test
    `-- system
        |-- router_test.go
        `-- template_test.go
```

I setup the router in system/router.go:
```
func (mr *Router) HandleStatic(urlPath string, dir string) {
	logger.Debug.Printf("Serving static files from '%s' on '%s'", dir, urlPath)

	mr.Handle(http.MethodGet, urlPath + "*f",
		http.StripPrefix(
			urlPath,
			CacheHandler(
				http.FileServer(
					packr.NewBox("./../" + dir),
				),
			),
		),
	)
}
```

This way in main.go:
```
r.HandleStatic("/static/", "public/assets/")
```

`public/assets/css/bootstrap.css` exists, but is not reachable from `/static/css/bootstrap.css`. (404)

Ideas?

**Comment by markbates** [comment]
https://golang.org/pkg/net/http/#StripPrefix

**Comment by HazCod** [comment]
@markbates My request url starts with /static

**Comment by markbates** [comment]
Yes. You need to strip the static prefix first. Look at the example in the link.

**Comment by HazCod** [comment]
Ah, well I am using `http.StripPrefix(...)` as you can see.

**Comment by markbates** [comment]
In the wrong place.

**Comment by HazCod** [comment]
What do you mean? The example in the docs does it comparably;
```
http.Handle("/tmpfiles/", http.StripPrefix("/tmpfiles/", http.FileServer(http.Dir("/tmp"))))
```

**Comment by markbates** [comment]
I’m on a phone, so I’m doing the best I can.

This problem is almost always because of two things StripPrefix not being used, or used in the wrong place, or you’re not pointing at the folder that you think you are.

Recheck both to ensure they’re correct.

You also have other things wrapped around it, so you could be confusing thing in there that aren’t known.

**Comment by markbates** [comment]
You’re problem, looking st it again is how you’re pathing the box. It can’t find it. 

See #106

**Comment by HazCod** [comment]
Interestingly, it works when I specify `../public/assets/`.
So relative paths are not supported before v2?

**Comment by markbates** [comment]
It can’t resolve a dynamic variable at compilation time. Either stop doing that, or pass a box in, the recommended approach.

**Comment by HazCod** [comment]
I see, thank you!
