### ISSUE TITLE
Problem with variables and packr.New

### ISSUE THREAD

**Issue by abenz1267** [gobuffalo/packr#108]
Hi,

so this doesn't work:

```
ahoi := "/test"
test := "." + ahoi
box := packr.NewBox(test)
```

while this would work:

```
test := "./test" 
box := packr.NewBox(test)
```

What am i missing? Latest version.

Regards

Edit: video (forgot to turn off music..sorry): https://drive.google.com/file/d/1ZE2Q09mnyp3XPGtT4abVJd5zoce2Dt1D/view?usp=sharing

**Comment by abenz1267** [comment]
apparently not an issue anymore with v2.

**Comment by mh-cbon** [comment]
I m having the problem with

```go
package main

var (
	WebAppDir = "client/public"
)

var (
	// migrationsBox = packr.New("migrations", "migrations")
	assetsBox = packr.NewBox(WebAppDir)
)
```

both packr and packr2 fails to detect the box : /

I intent to write it this way so the directory is rewritable with ldflags.
