### ISSUE TITLE
packr2 ignores go.mod

### ISSUE THREAD

**Issue by MMulthaupt** [gobuffalo/packr#113]
I have a project with a `go.mod` which sets the project root to `gitlab.mymachine.lan/foo/project` using the `module` keyword. After running the command `packr2` the `packrd` folder is created with the packed file contents as well as the `main-packr.go` in the project root. However, the blank import in the file is wrong. I'd expect it to be `import _ "gitlab.mymachine.lan/foo/project/packerd"`, but it is `import _ "home/myuser/gitlab/project/packrd"`. Continuing with `go build` fails as one would then expect: `build gitlab.mymachine.lan/foo/project: cannot find module for path home/myuser/gitlab/project/packrd`. Fixing the import beforehand results in everything being built correctly. I would prefer to get this to work without having to consult the likes of `sed`.

**Comment by Zyl9393** [comment]
Note that there is a second way besides setting `GO111MODULE` to `on` to enable module support. From [Golang Wiki](https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support):

> Invoke the `go` command in a directory outside of the `$GOPATH/src` tree, with a valid `go.mod` file in the current directory or any parent of it and the environment variable `GO111MODULE` unset (or explicitly set to `auto`).

I don't see the `Mods()` function in `envy` respect this. Will test this on Monday.

**Comment by markbates** [comment]
We only support explicit turning on of Go modules at this point.

You must ACTUALLY opt-in.

That’s standard across all the orgs repos, and we won’t be changing that; for a variety of reasons.
