### ISSUE TITLE
packr2 traverses non existing paths when vendoring

### ISSUE THREAD

**Issue by zerkms** [gobuffalo/packr#123]
```
➜ packr2 version
v2.0.0-rc.8
```

I created a repository with a reproduction: https://github.com/zerkms/packr2-godirwalk-bug

Steps to reproduce:

1. Clone https://github.com/zerkms/packr2-godirwalk-bug
2. Run `packr2`

Expected: it should generate a box with the `resources` directory

Actual: 
```
Error: cannot Stat: stat /tmp/packr2-godirwalk-bug/vendor/github.com/karrick/godirwalk/testdata/dir3/zzz: no such file or directory
```

**Comment by zerkms** [comment]
Oh, that was quick. I was about to check if I can PR myself later today :-D

Thanks!

**Comment by markbates** [comment]
No problem. Thanks for the super easy to repro steps. That made it quick to figure it out.
