### ISSUE TITLE
packr2 uses absolute paths

### ISSUE THREAD

**Issue by ajruckman** [gobuffalo/packr#125]
`packr2` creates `main-packr.go` with
```
import _ "T:/absolute/path/to/project/directory/packrd"
```
 rather than using a relative path like 
```
import _ "./packrd"
```
which of course doesn't work on Windows.

After running `packr2` I can of course manually edit `main-packr.go` to make it use the relative path, but after compiling, `box.FindString` seems like it tries to read the file on the disk itself? But errors when it can't find it. 

So if I run the program on my local machine, it works fine because it has access to `T:\absolute\path\to\project\directory\templates`, but it errors on remote machines:

```
2018/12/04 14:20:42 http: panic serving x.x.x.x:60036: FindFirstFile T:\absolute\path\to\project\directory\templates\base.html: The system cannot find the path specified.
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc00063b720)
        D:/dev/go/goroot/src/net/http/server.go:1746 +0xd7
panic(0x994a40, 0xc00005d440)
        D:/dev/go/goroot/src/runtime/panic.go:513 +0x1c7
...
net/http.HandlerFunc.ServeHTTP(0xa6e308, 0xaefb60, 0xc00062b420, 0xc000100200)
        D:/dev/go/goroot/src/net/http/server.go:1964 +0x4b
net/http.(*ServeMux).ServeHTTP(0xf822a0, 0xaefb60, 0xc00062b420, 0xc000100200)
        D:/dev/go/goroot/src/net/http/server.go:2361 +0x12e
net/http.serverHandler.ServeHTTP(0xc000492dd0, 0xaefb60, 0xc00062b420, 0xc000100200)
        D:/dev/go/goroot/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc00063b720, 0xaf0520, 0xc000040380)
        D:/dev/go/goroot/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
        D:/dev/go/goroot/src/net/http/server.go:2851 +0x2fc
```
All of this works fine in `packr` but does not in `packr2`.

**Comment by markbates** [comment]
Can you please provide a reproducible example case?

Thank you.

**Comment by ajruckman** [comment]
My apologies, I couldn't share much more info about the code that caused it above. I will work on a reproducible version as soon as I can.

**Comment by ajruckman** [comment]
Here you go: https://gist.github.com/ajruckman/23f01c441446b51d688f221b88ce33a1

`base.html` goes in "./templates". 

To reproduce:
- Use Windows
- cd to project directory
- `packr2`
- See that `main-packr.go` uses an absolute path to `./packrd`
- `go build` - will fail:
```
can't load package: package .:
main-packr.go:7:10: invalid import path: "T:/absolute/path/to/PackrDemo/packrd"
```
- Edit `main-packr.go` to use a relative path to `./packrd`: 
Change `import _ "T:/absolute/path/to/PackrDemo/packrd"` to `import _ "./packrd"`
- `go build` - will succeed
- `.\PackrDemo.exe` - will work

I'm still trying to figure out why my original project works fine on my local computer but fails when the project directory containing the templates isn't accessible. I might be doing something wrong there so I may not be able to reproduce that part.

**Comment by markbates** [comment]
Can you confirm you’re using v2.0.0-rc.10?

**Comment by ajruckman** [comment]
I am

**Comment by markbates** [comment]
Using your example on Windows. I can't reproduce.

My file looks like:

```
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package main

import _ "github.com/gobuffalo/mysite/packrd"
```

All of the windows tests pass on travis as well, https://travis-ci.org/gobuffalo/packr/builds/464111847

That would mean that it something environmental causing packr to produce strange results. 

My guess it is has something to do with your `T:` drive not being returned via this https://golang.org/pkg/go/build/#Context.SrcDirs That is used to convert your projects location into a Go package. If your project's location isn't being reported there it could lead to in-correct file information.

**Comment by ajruckman** [comment]
I tried moving it to my C: drive but it still doesn't work:

```
PS C:\PackrDemo> go clean
PS C:\PackrDemo> packr2 clean
PS C:\PackrDemo> packr clean
PS C:\PackrDemo> ls


    Directory: C:\PackrDemo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        12/6/2018  12:47 PM                .idea
d-----        12/6/2018  12:47 PM                templates
-a----        12/6/2018   8:44 AM            815 demo.go


PS C:\PackrDemo> packr2
PS C:\PackrDemo> ls


    Directory: C:\PackrDemo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        12/6/2018  12:47 PM                .idea
d-----        12/6/2018  12:47 PM                packrd
d-----        12/6/2018  12:47 PM                templates
-a----        12/6/2018   8:44 AM            815 demo.go
-a----        12/6/2018  12:47 PM            210 main-packr.go


PS C:\PackrDemo> gc .\main-packr.go
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package main

import _ "C:/PackrDemo/packrd"
PS C:\PackrDemo> go build
can't load package: package .:
main-packr.go:7:10: invalid import path: "C:/PackrDemo/packrd"
```

Your `main-packr.go` is importing from GitHub and mine is importing from a local directory, do you know why that might be?

**Comment by markbates** [comment]
What is the output of go env?

I’m guessing you’re working outside of a GOPATH and that is your problem.

If you’re using modules; them that’s a whole nother set of questions.

--
Mark Bates
CTO/Founder

**Comment by ajruckman** [comment]
AFAIK I am not using modules.

```
PS C:\PackrDemo> go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ajr21067\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\dev\go\gopath
set GOPROXY=
set GORACE=
set GOROOT=D:\dev\go\goroot
set GOTMPDIR=
set GOTOOLDIR=D:\dev\go\goroot\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ajr21067\AppData\Local\Temp\go-build496603830=/tmp/go-build -gno-record-gcc-switches
```

**Comment by markbates** [comment]
That’s the problem. You’re our not inside your GOPATH. Go requires you to work with your GOPATH/src directory. You are outside of your GOPATH so things aren’t compiling correctly for you.

Move inside your GOPATH and your problems should resolve.

--
Mark Bates
CTO/Founder

**Comment by ajruckman** [comment]
I never knew that... I have always written my code in directories outside my gopath without a problem. I understand now that's the supported and correct way to write code. However, if it wouldn't hurt anything else, would it make sense to use a relative directory for `packrd` instead? Either way this issue is resolved. Thank you!

**Comment by ajruckman** [comment]
Related: https://github.com/golang/dep/issues/1441

Also from here: https://softwareengineering.stackexchange.com/questions/271324/is-having-source-code-for-a-go-project-outside-gopath-a-bad-idea
`You are not required to use GOPATH, but then you miss out on all the nice tooling that you get from the go command. They all expect code to be in the standard GOPATH hierarchy.`

**Comment by markbates** [comment]
If you write main’s that use the std lib; you can. It’s importing other packages that causes the problem. 

You can use the —legacy flag and that will generate the file in the main package for you, v1 style.

**Comment by midstar** [comment]
I have exactly the same problem. packr works fine in my Windows PC, but not on Appveyor. 

When running on Appveyor I always get absolute paths on Windows.

Linux is no problem on my Linux machine nor on Appveyor.

I tried packr2 --legacy and still my application did not include the binaries on Appveyor.

Note that I have my project in the GOPATH/src directory. go env shows that GOPATH is correct.

The only solution I have so far is to override main-packr.go with my own modded main-packr.go file.

**Comment by lalloni** [comment]
We've been bitten by this same issue.

Note that since GO111MODULES is valid and expected to be common to work outside GOPATH. Here, we're migrating all projects to using modules.

Unfortunately this problem rules out packr for us.

**Comment by midstar** [comment]
Unfortunately my workaround (to mod the main-packr.go file) don't work for packr2 anymore. When packr2 believes that the project is outside GOPATH (which it is not) packr2 now fails instead of creating an absolute path import as it did before. The error is:

    packr2 
    Error: You appear to be working outside of your GOPATH and do not have GO111MODULE set to "on".
    Packr, and all of the github.com/gobuffalo projects, require you to opt-in to using Go modules.

See the build results from my project:

https://ci.appveyor.com/project/midstar/mediaweb/builds/23547484/job/f66f4jkchdbpy76s

It seems that Appveyor does something with its file system so that packr2 thinks that you are outside GOPATH. Unfortunately my only option was to switch to go.rice instead of packr2, which don't have this issue but have a quite similar interface.
