### ISSUE TITLE
making a box for a directory above this one doesn't work 

### ISSUE THREAD

**Issue by natefinch** [gobuffalo/packr#13]
making a box of a directory that is not a subdirectory of this directory doesn't work:
e.g.
```go
box := packr.NewBox("../public")
```
See https://github.com/natefinch/markbates/blob/master/test/test.go#L13

And by doesn't work, I mean that if you remove the folder after generating the packr.go file for it, the built executable fails to find those files.  You can test it by running packr install for github.com/natefinch/markbates ... if you run markbates then, it'll open up a webpage saying "hi mark!"  if you then rename the public directory to something else, running markbates will open up a 404 page

**Comment by natefinch** [comment]
actually, this seems to happen for sub directories as well, which means I'm misunderstanding something.

```go
	box := packr.NewBox("./public")

	http.Handle("/", http.FileServer(box))
	fmt.Println("serving docs at http://localhost:8080")
	fmt.Println("hit ctrl-C to cancel")
	go browser.OpenURL("http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", nil))
```

^^ This will serve up what's in ./public if the folder exists, but if I remove the folder, it gives me 404s.

**Comment by natefinch** [comment]
note that this is *after* running packr, while having a packer file that looks like this:

```go
func init() {
	packr.PackJSONBytes("./public", "index.html", "\"SGkgTWFyayE=\"")
	}
```

**Comment by markbates** [comment]
Looks like the problem actually has to do with how `http.FileServer` handles `index.html` files:

```
http.Handle("/", http.FileServer(http.Dir("/tmp")))
As a special case, the returned file server redirects any request ending in "/index.html" to the same path, without the final "index.html".
```

**Comment by natefinch** [comment]
oh man, that is crazy town.  Thanks for figuring this out :)

**Comment by markbates** [comment]
lol. Tell me about it! I had to dig deep to figure how to make it work. They’re doing some really strange things in the http package.

**Comment by shurcooL** [comment]
If you want an `http.FileServer`-like construct with without special handling of `index.html` files, it's quite easy to make your own. You can see an example of one I've created at https://godoc.org/github.com/shurcooL/httpgzip#FileServer.
