### ISSUE TITLE
go get -u installation is taking a long time

### ISSUE THREAD

**Issue by sishilong** [gobuffalo/packr#132]
Hi, thanks for this awesome tool!
just want to get some help on this
this installation command is taking a really long time to finish, do we need to use -u for this command?$ time go get -u github.com/gobuffalo/packr/packr
real	0m30.724s
user	0m6.162s
sys	0m6.558s

and it takes around the same even when we run the second time.

**Comment by markbates** [comment]
This appears to be an environmental issue.
