### ISSUE TITLE
duplicate Boxes results in duplicates in packr.go file

### ISSUE THREAD

**Issue by kmanley** [gobuffalo/packr#137]
I transitioned a server from bindata-assetfs to packr, this server had multiple embedded webservers listening on different ports so I had essentially 5 calls to 
```go
box := packr.NewBox("../static")
```
I was surprised to see all the assets included 5 times in the generated packr file. I can certainly change my code to only create one box and pass it around, but maybe it would be good for packr to eliminate duplicates in situations like this.

**Comment by markbates** [comment]
Fixed in v2.
