### ISSUE TITLE
packr2 not parsing flags correctly

### ISSUE THREAD

**Issue by AndyPWarren** [gobuffalo/packr#141]
Hi. I have my application entry point (main.go) in a subdirectory e.g. cmd/main.go and the repo is using go modules. When I run `packr2 build -v cmd/main.go` it complies the binary fine but it cant find the boxes I setup in the main.go `DEBU[2019-01-15T09:49:14Z] found 0 boxes`

**Comment by AndyPWarren** [comment]
I have tried cd'ing into the cmd directory and running `packr2` but it complains it can't find the `go.mod` file as I have set `GO111MODULE=on`

**Comment by markbates** [comment]
Can you provide a working example and the output of of the commands with -v?

Packr2 follows import paths to find boxes, if you’re not importing a package it won’t find you boxes. If you want the old style, folder walking, then use the skip imports flag.

**Comment by AndyPWarren** [comment]
Thanks for the hint about imports. I have got this working now but for other stumbling across this.
I have the following directory structure (a common structure for Cobra CLI projects, although simplified for the purpose of this example)
```
- cmd/
-- main.go
- templates/
-- hello.txt
- go.mod
- go.sum
```
Here's the basic `main.go` file to demonstrate the issue
```
package main

import (
	"fmt"
	"log"

	"github.com/gobuffalo/packr/v2"
)

func main() {
	box := packr.New("templates", "../templates")
	s, err := box.FindString("hello.txt")
	if err != nil {
		log.Fatalf("error finding string: %v", err)
	}
	fmt.Println(s)
}
```
I set go module support:
`export GO111MODULE=on`
in the module root directory I run packr2 with ignore imports 
`packr2 --ignore-imports -v`
Then build it normally with go
`go build cmd/main.go`
then clean up the generated files
`packr2 clean`

**Comment by AndyPWarren** [comment]
Although I couldn't get ignore imports to work with the packr2 build command
`packr2 --ignore-imports build -v cmd/main.go`
I get the following error
`flag provided but not defined: -ignore-imports`

**Comment by dom3k** [comment]
I have the same. Flag `--ignore-imports` is not recognize.

**Comment by tomhughesnice** [comment]
I found 
`packr2 --ignore-imports build  cmd/main.go` would always fail with the error
`flag provided but not defined: -ignore-imports`

Breaking up the command worked though.
```
packr2 --ignore-imports build
go build  cmd/main.go
```

**Comment by markbates** [comment]
If someone would like to open a PR to fix this, it would be very welcome, otherwise It’ll be a bit before I can get to this. I’m backed up at work.
