### ISSUE TITLE
Adding support for power(ppc64le) arch

### ISSUE THREAD

**Issue by ghatwala** [gobuffalo/packr#142]
Hi All,

We need power binaries of "packr" as a requirement for argocd - https://github.com/argoproj/argo-cd/blob/master/Dockerfile#L39  supported at the releases page of this repo.

I am able to build this go based repo successfully on my power machine

```
~/gopath/src/github.com/gobuffalo/packr# arch
ppc64le

~/gopath/src/github.com/gobuffalo/packr# git branch
* master

~/gopath/src/github.com/gobuffalo/packr# packr version
v1.21.9

~/gopath/src/github.com/gobuffalo/packr# file /root/gopath/bin/packr
/root/gopath/bin/packr: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=f721b43db6a941560f8163cdd9ed3f8630a2eee4, not stripped

~/gopath/src/github.com/gobuffalo/packr# go version
go version go1.11.4 linux/ppc64le
```
Let me know of the method/way to contribute here to get power equivalent binaries added here.

**Comment by markbates** [comment]
changes to built binaries, for Packr v2, can be made here https://github.com/gobuffalo/packr/blob/master/v2/.goreleaser.yml.plush. More information on the goreleaser tool can be found here: https://goreleaser.com

**Comment by ghatwala** [comment]
Closing this as thi PR - https://github.com/gobuffalo/packr/pull/143 merged and also power binary showing under releases - https://github.com/gobuffalo/packr/releases/download/v2.0.0-rc.15/packr_2.0.0-rc.15_linux_ppc64le.tar.gz
