### ISSUE TITLE
packr tool cannot find packr.NewBox

### ISSUE THREAD

**Issue by alex920** [gobuffalo/packr#15]
```
package main

import (
	"github.com/gobuffalo/packr"
)

type S struct{}

func (S) f(packr.Box) {}

func main() {
	s := S{}
	s.f(packr.NewBox("test"))
}
```

Packr is not generating main-packr.go because it cannot find packr.NewBox.

Temporary solution: assign value of function packr.NewBox to variable and use that variable in s.F.

**Comment by markbates** [comment]
Great find! Thanks.
