### ISSUE TITLE
Feature Request: Optionally have build tags in generated files

### ISSUE THREAD

**Issue by techknowlogick** [gobuffalo/packr#153]
First, Thanks for packr 😄 it is great.

As title. Right now I append the build tags after running packr, and it would be nice to have that all as one step.

**Comment by techknowlogick** [comment]
Hi @markbates. I don't mean when building the binary, but when generating the `*-packr.go` files

**Comment by markbates** [comment]
Re-opened now that I understand the request. Can I ask the use case for this? Would generating `// +build !skip-packr` work?

**Comment by techknowlogick** [comment]
Use case: I'm one of the leads of [Gitea](https://github.com/go-gitea/gitea), and to distribute our software on some OSes we can't compile static assets into the binary if we want our .deb to be added to the official channel, and so right now we are using bindata and have a TAG to include the bundled static assets in the binary.

Looking into this I'm guessing that this file: https://github.com/gobuffalo/packr/blob/master/v2/jam/store/disk_tmpl.go is the right place to add the above build tag you suggested. I can create a PR for this today if that's the case.

Thanks again 😄

**Comment by markbates** [comment]
PRs are totally welcome! :)

-----------
Mark Bates
