### ISSUE TITLE
Ability to unpack box

### ISSUE THREAD

**Issue by UlisseMini** [gobuffalo/packr#157]
I am making a code generation tool and packr is very useful for all my templates, except i would like my users to be able to edit the templates on disk; so what i'm trying to do is unpack my box of templates into a folder `~/.goc/templates`

However `box.List()` and `box.Walk` only work with files. what would be nice is a library function `box.Unpack(dst string) error` that unpacks a box into a new directory.

If i'm just being dumb and there is an easy way to do this please tell me and this issue can be closed thanks!

**Comment by markbates** [comment]
`box.Walk` takes a function that will walk through all of the files in your box, whether packed in the binary or on disk, with that you can unpack your files anywhere, and any how you'd like.

**Comment by markbates** [comment]
You might want to check out https://github.com/gobuffalo/genny which is a code generation tool, that's easy to test, and can generate files from a `packr.Box`.

**Comment by UlisseMini** [comment]
Okay thank you!

**Comment by UlisseMini** [comment]
To be clear i was having issues with finding what directories are in the box, for example with this directory layout:
```
dir
dir/subdir
dir/subdir/someotherfile
dir/somefile
```
and this code
```go
	box := packr.New("test", "dir")

files := box.List()
for _, file := range files {
	fmt.Printf("walk: %s\n", file)
}
```
Outputs
```
walk: somefile
walk: subdir/someotherfile
```instead of
```
walk: somefile
walk: subdir/someotherfile
walk: subdir (the folder)
```

**Comment by markbates** [comment]
`box.List` only returns a list of the files inside your box. For access to the files themselves you need to use `box.Walk`. The directory is part of a file's name. Use `filepath.Dir` to get the name of a file's directory.

**Comment by UlisseMini** [comment]
Oh thanks! i did not know about `filepath.Dir`, that makes what i'm doing much easier :)
