### ISSUE TITLE
How to use packr with ParseGlob

### ISSUE THREAD

**Issue by farazfazli** [gobuffalo/packr#16]
How to use packr with ParseGlob? Right now I'm trying to use Packr with html/template ParseGlob by just accessing the Path, but it isn't working...how would this be done? I don't want to parse each string manually..would that be necessary?

```
templates := packr.NewBox("./templates")
tpl = template.Must(template.New("").ParseGlob(templates.Path + "/*.gohtml"))
```

**Comment by markbates** [comment]
ParseGlob reads files from disk. When you bundle the templates in a binary they’re no longer on disk, so you can’t use ParseGlob.

**Comment by rskumar** [comment]
For loading all templates from box, you can `walk` box items and parse+register template yourself.
Something like this - 

```golang

t := template.New("")
err := box.Walk(func(p string, f packr.File) error{
	// skip all files except .html
	if !strings.Contains(p, ".html"){
		return nil
	}

	var h []byte
	if _, err := f.Read(h); err != nil {
		return err
	}

	// Normalize template name
	n := p
	if strings.HasPrefix(p, "\\") || strings.HasPrefix(p, "/") {
		n = n[1:]		// don't want template name to start with / ie. /index.html
	}
	// replace windows path seperator \ to normalized /
	n = strings.Replace(n, "\\", "/", -1)

	if _, err := t.New(n).Parse(string(h)); err != nil {
		return err
	}
	return nil
})
```
