### ISSUE TITLE
Optional Box

### ISSUE THREAD

**Issue by leaanthony** [gobuffalo/packr#160]
I have an situation where my app runs in 2 modes based on a cli flag. In one mode I want to use a box, in the other i do not. Currently, if I build when the path doesn't exist on disk (using the packr command), it aborts.

It would be great if there's a way of indicating to the cli that i'm cool with it not existing.

**Comment by markbates** [comment]
What version of Packr are you using?

Can you provide an example of what you're doing?

**Comment by markbates** [comment]
Working with non-existent folders on disk is supported in v2, so I can't reproduce without further information. If you aren't using v2, please upgrade.

**Comment by leaanthony** [comment]
Ah, i was actually holding off from upgrading to v2 but great that it's
supported.

Will upgrade. Sorry for the noise.

**Comment by leaanthony** [comment]
Looks like v2 doesn't support modules. Any plans for that?

**Comment by markbates** [comment]
Both v1 and v2 support modules. There are go.mod files in both.

-----------
Mark Bates

**Comment by markbates** [comment]
https://github.com/gobuffalo/packr/blob/master/v2/go.mod
