### ISSUE TITLE
packr2: Open returns not found for paths starting with / (directory)

### ISSUE THREAD

**Issue by dkumor** [gobuffalo/packr#161]
Given the following file system:
```
mytest/
    index.html
```

The query `box.Open("mytest")` succeeds, but `box.Open("/mytest")` fails. 

`Resolve` works for both queries. 

This is an issue because `http.FileServer` runs an `Open("/mytest")` when navigating to `/mytest/`. The page will give a 404 when it should show index.html. Same is true when there is no `index.html`: it should list the folder contents.

**Comment by markbates** [comment]
PRs are welcome.

-----------
Mark Bates
