### ISSUE TITLE
packr2: file Readdir returns self

### ISSUE THREAD

**Issue by dkumor** [gobuffalo/packr#162]
The `http.File` interface requires `Readdir`, which is used to list a folder in `FileServer` when `index.html` is not present.

Currently, packr's `file.Readdir` which comes from `box.Open` returns just a single entry, the directory name itself, see: https://github.com/gobuffalo/packd/blob/master/file.go#L41

This means that `Readdir` does not actually read the directory, making it impossible to use.

I specifically got caught with this trying to copy a packed folder to the filesystem recursively - `Readdir` was returning the same folder as its own child.

**Comment by markbates** [comment]
PRs are welcome.

-----------
Mark Bates
