### ISSUE TITLE
`box.Open` cannot open files without extensions

### ISSUE THREAD

**Issue by Ferguzz** [gobuffalo/packr#166]
```	
if len(filepath.Ext(name)) == 0 {
		if !b.HasDir(name) {
			return nil, os.ErrNotExist
		}
```
this means if i have a script which just has a filename like `scripts/foo`, `box.Open` thinks it's a directory which doesn't exist and returns the `ErrNotExist` error.

**Comment by markbates** [comment]
PRs are most definitely welcome. :)

**Comment by markbates** [comment]
Dup of #159
