### ISSUE TITLE
Incorrect processing of GOPATH 

### ISSUE THREAD

**Issue by omzlo** [gobuffalo/packr#172]
It seems packr v2 does not process GOPATH correctly.
On my system (OSX) I have:

```
> echo $GOPATH
/Users/pannetra/Go
```

```
> go version
go version go1.12 darwin/amd64
```

```
> packr2 version
v2.0.3
```

However, when I run packr2 I get:
```
packr2 build nocanc.go 
/Users/pannetra/Go/src/github.com/omzlo/nocanc/webui/webui-packr.go:8:8: cannot find package "Users/pannetra/go/src/github.com/omzlo/nocanc/cmd/packrd" in any of:
	/usr/local/go/src/Users/pannetra/go/src/github.com/omzlo/nocanc/cmd/packrd (from $GOROOT)
	/Users/pannetra/Go/src/Users/pannetra/go/src/github.com/omzlo/nocanc/cmd/packrd (from $GOPATH)
Error: exit status 1
Usage:
  packr2 build [flags]

Flags:
  -h, --help   help for build

Global Flags:
      --ignore-imports     when set to true packr won't resolve imports for boxes
      --legacy             uses the legacy resolution and packing system (assumes first arg || pwd for input path)
      --silent             silences all output
      --store-cmd string   sub command to use for packing
  -v, --verbose            enables verbose logging

```

I found a temporary fix by simply running:
```
GOPATH="" packr2 build nocanc.go 
```
But it does not feel right.

**Comment by markbates** [comment]
Your GOPATH has a capital Go. You’re file system has a lower case go. Fix one and the problem will resolve itself.

**Comment by omzlo** [comment]
Ooops. You're right, sorry. Strangely Mac OS X doesn't care if you do `cd Go` or `cd go` and will change into the same directory. The go tools don't seem to care either.

**Comment by markbates** [comment]
If you use a go.mod it doesn’t matter. We have to try and figure out a package based on the file path, the Go tools don’t have to do that. That’s why they need to match. We strip the GOPATH from pwd and get your package. If they don’t match, the strip doesn’t work.
