### ISSUE TITLE
box.open open "/" return dir

### ISSUE THREAD

**Issue by zcx2001** [gobuffalo/packr#173]
now box.Open("/") is return a file (isDir is false) and err is nil  
on `http.serveFile` the code in `net/http/fs.go`
```
	if redirect {
		// redirect to canonical path: / at end of directory url
		// r.URL.Path always begins with /
		url := r.URL.Path
		if d.IsDir() {
			if url[len(url)-1] != '/' {
				localRedirect(w, r, path.Base(url)+"/")
				return
			}
		} else {
			if url[len(url)-1] == '/' {
				localRedirect(w, r, "../"+path.Base(url))
				return
			}
		}
	}

	// redirect if the directory name doesn't end in a slash
	if d.IsDir() {
		url := r.URL.Path
		if url[len(url)-1] != '/' {
			localRedirect(w, r, path.Base(url)+"/")
			return
		}
	}

	// use contents of index.html for directory, if present
	if d.IsDir() {
		index := strings.TrimSuffix(name, "/") + indexPage
		ff, err := fs.Open(index)
		if err == nil {
			defer ff.Close()
			dd, err := ff.Stat()
			if err == nil {
				name = index
				d = dd
				f = ff
			}
		}
	}	
}
```
code is redirect to "/" not “/index.html"

i fix the code in `func (b *Box) Open(name string) (http.File, error)` is 
```
        plog.Debug(b, "Open", "name", name)
        if strings.EqualFold("/", name) {
		return file.NewDir("/")
	}
	f, err := b.Resolve(name)
	if err != nil {
		if len(filepath.Ext(name)) == 0 {
			return b.openWoExt(name)
		}
		return f, err
	}
	f, err = file.NewFileR(name, f)
	plog.Debug(b, "Open", "name", f.Name(), "file", f.Name())
	return f, err
```

**Comment by vadimpiven** [comment]
The problem is directories are not detected at all. Example program:
```
package main

import (
	"fmt"
	"github.com/gobuffalo/packr/v2"
)

func main() {
	s := packr.New("static", "static")
	f, err := s.Open("/dir")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(f)
		fmt.Println(f.Readdir(0))
	}
}
```
Wether you build with `go build` or `packr2 build` it's output is:
```

[{/dir/ 0 {13771438225996173496 3532839 0x17af2c0} false}] <nil>
```
And `ls -R` output in project directory is:
```
main.go static

./static:
dir        index.html test.html

./static/dir:
index.html test.html
```

**Comment by vadimpiven** [comment]
I've found a solution. [This](https://github.com/gobuffalo/packr/blob/master/v2/box.go#L145) line of code should be replaced with

	info, err := f.FileInfo()
	if err != nil {
		return f, err
	}
	if info.IsDir() {
		f, err = file.NewDir(name)
	} else {
		f, err = file.NewFileR(name, f)
	}

and [this](https://github.com/gobuffalo/packr/blob/master/v2/box.go#L221) line should be replaced with

	info, err := f.FileInfo()
	if err != nil {
		return f, errors.WithStack(err)
	}
	if info.IsDir() {
		f, err = file.NewDir(key)
	} else {
		f, err = file.NewFile(key, b)
	}

It worked for me, but I'm not sure is it a complete solution.

**Comment by matthijskooijman** [comment]
I've also seen `Open("/")` return success, but a file descriptor rather than a directory descriptor. I suspect that this might prevent `net/http` from translating the `/` url into `/index.html` internally (since it only appends `index.html` for directories), so perhaps that is also why `Box::openWoExt` exists (which seems like the wrong place to handle adding `index.html`).

Also, I suspect this might tie in with #192, which points out some other places where the responsibilities are (AFAICS) not very well defined and divided between box, resolvers and others.

**Comment by Lesterpig** [comment]
Hello, this looks like a severe issue. From my understanding, the README example (https://github.com/gobuffalo/packr#usage-with-http) does not work anymore for `index.html` files.

Is there any elegant way to tackle that in the current version? Thanks! :+1:

**Comment by markbates** [comment]
It supports it.

**Comment by Lesterpig** [comment]
> It supports it.

Sorry, but no, it's not; or I'm not understanding something here :disappointed: 
I just created a file in my GOPATH, copied the `main.go` file from the README, and added a `templates` directory:

```bash
$ tree .
.
├── main.go
└── templates
    ├── index.html
    └── test.html
```

I cannot access index.html, but test.html works fine.

```bash
$ go version
go version go1.12.4 linux/amd64
$ cd $GOPATH/src/github.com/gobuffalo/packr/v2 && git describe --tags
v2.1.0
```

**Comment by markbates** [comment]
https://github.com/gobuffalo/packr/blob/master/v2/http_box_test.go

-----------
Mark Bates

**Comment by sagikazarmark** [comment]
@markbates I've run the tests, they pass. Then exchanged the resolver with a disk resolver. Tests fail.

I'm trying to figure out what's going on.

**Comment by sagikazarmark** [comment]
As far as I can tell the difference is the `HexGzip` used in the test returns an error when you try to resolve the "/" path, whereas the `Disk` resolver returns a directory.

Here is the relevant code: https://github.com/gobuffalo/packr/blob/e0e2368a6595d66ce4fc31d3c2d1e8575293885e/v2/box.go#L146-L153

So I think this is a valid issue after all.

**Comment by sagikazarmark** [comment]
Pushed an experimental fix

**Comment by sagikazarmark** [comment]
This seems to be a workaround:

```
func (b *binaryFileSystem) Open(name string) (http.File, error) {
	// This is necessary because of https://github.com/gobuffalo/packr/issues/173
	if b.fs.HasDir(name) {
		return file.NewDir(name)
	}

	return b.fs.Open(name)
}
```
