### ISSUE TITLE
packr2 does not find boxes when package main is in subdirectory in modules setup

### ISSUE THREAD

**Issue by Jarema** [gobuffalo/packr#175]
Hi.

Im using packr2 with app using modules.

`GO111MODULE=on` is exported.

The package main is in `$PROJECT_ROOT/cmd/app`

Executing `packr2 ./cmd/app` with verbose flag says it found 0 boxes. Even if path to files is absolute.

When I move package main to root of the project, all works as expected.

Though, I don't want to have package main in root of my project, as I have many binaries for it.

Any suggestions how to have packr2 working in such case?

**Comment by markbates** [comment]
It doesn’t matter where you’re main is. You just need to run the tool from the root of your project where the go.mod is.

**Comment by Jarema** [comment]
@markbates  It does matter for boxes found.

When I build in subdir:

```
 packr2 build -v ./cmd/hilo/
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots options="{\"IgnoreImports\":false,\"Ignores\":null}" roots="[\"/Users/tomaszpietrek/coding/hilo-app\"]"
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots walking=/Users/tomaszpietrek/coding/hilo-app
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots found prospects=0
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots options="{\"IgnoreImports\":false,\"Ignores\":null}" roots="[\"/Users/tomaszpietrek/coding/hilo-app\"]"
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots walking=/Users/tomaszpietrek/coding/hilo-app
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots found prospects=0
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots options="{\"IgnoreImports\":false,\"Ignores\":null}" roots="[\"/Users/tomaszpietrek/coding/hilo-app\"]"
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots walking=/Users/tomaszpietrek/coding/hilo-app
DEBU[2019-03-18T18:48:52+01:00] *parser.Parser#NewFromRoots found prospects=0
DEBU[2019-03-18T18:48:52+01:00] found 0 boxes
DEBU[2019-03-18T18:48:52+01:00] *store.Disk#Close
DEBU[2019-03-18T18:48:52+01:00] Step: d6bd6c34
DEBU[2019-03-18T18:48:52+01:00] Chdir: /Users/tomaszpietrek/coding/hilo-app
DEBU[2019-03-18T18:48:52+01:00] go build -v ./cmd/hilo/
```
versus building in the root (the content of the main.go are the same. path to boxes are absolute to be sure)

```
...
DEBU[2019-03-18T18:50:19+01:00] *parser.Parser#Run parsing=/Users/tomaszpietrek/go/src/github.com/rs/zerolog/syslog.go
DEBU[2019-03-18T18:50:19+01:00] found 2 boxes
DEBU[2019-03-18T18:50:19+01:00] *store.Disk#Pack box=/Users/tomaszpietrek/coding/hilo-app/trees
DEBU[2019-03-18T18:50:19+01:00] *store.Disk#Pack box=/Users/tomaszpietrek/coding/hilo-app/trees
DEBU[2019-03-18T18:50:19+01:00] *store.Disk#Close
DEBU[2019-03-18T18:50:19+01:00] Step: 9f4b7c7f
DEBU[2019-03-18T18:50:19+01:00] Chdir: /Users/tomaszpietrek/coding/hilo-app
DEBU[2019-03-18T18:50:19+01:00] File: /Users/tomaszpietrek/coding/hilo-app/packrd/packed-packr.go
DEBU[2019-03-18T18:50:19+01:00] File: /Users/tomaszpietrek/coding/hilo-app/cmd/hilo/main-packr.go
DEBU[2019-03-18T18:50:19+01:00] go build -v
gitlab.vodeno.com/vodeno/history-log/hilo```

**Comment by Jarema** [comment]
@markbates what is even more weird, plain `packr2` command in root directory founds nothing, but if I put empty `package main` with noop main function, it finds the box.

**Comment by Mik-** [comment]
Hi,
I have exactly the same issue. I put a demo repo [here](https://github.com/Mik-/packr2-test).

If I call 
```
GO111MODULE=on packr2 -v build -o bin/packr2-test github.com/Mik-/packr2-test/cmd/packr2-test
```
it results in `found 0 boxes`.

I can use two workarounds:
1. Enter the subdirectory and call packr2 from there
1. Create an almost empty main.go in the root (as @Jarema stated)

Did I overlook something or is this still a bug?

**Comment by markbates** [comment]
If there aren’t any go files in the directory you run packr in it can’t walk the imports of the project. 

You have to run it in a directory where you have actually code you want to pack boxes for.

**Comment by markbates** [comment]
If you want folder walking use —skip-imports

**Comment by batazor** [comment]
@markbates I encountered the same problem and was unable to find a way to solve it.

```
> packr2 build -o test -v cmd/hcfc/main.go --ignore-imports

...
DEBU[2019-04-02T16:39:04+03:00] *parser.Parser#NewFromRoots found prospects=0
DEBU[2019-04-02T16:39:04+03:00] found 0 boxes
DEBU[2019-04-02T16:39:04+03:00] *store.Disk#Close
DEBU[2019-04-02T16:39:04+03:00] Step: 57dc87c4
DEBU[2019-04-02T16:39:04+03:00] Chdir: /home/batazor/.gvm/pkgsets/go1.12/global/src/github.com/batazor/hcfc
DEBU[2019-04-02T16:39:04+03:00] go build -v cmd/hcfc/main.go
````

repo: https://github.com/batazor/hcfc/blob/master/pkg/templates/templates.go

**Comment by markbates** [comment]
Run packr in the folder where your main.go files. It can’t find any imports, because there aren’t any .go files wherever you’re running it.

**Comment by batazor** [comment]
I read the discussion above, unfortunately going to the `cmd/hcfc` folder or moving `main.go` to the root of the project leads to the same result

```
> cd cmd/hcfc/
> packr2 build -v main.go --ignore-imports

...
DEBU[2019-04-03T11:22:05+03:00] found 0 boxes
DEBU[2019-04-03T11:22:05+03:00] *store.Disk#Close
DEBU[2019-04-03T11:22:05+03:00] Step: 3a0a9d09
DEBU[2019-04-03T11:22:05+03:00] Chdir: /home/batazor/.gvm/pkgsets/go1.12/global/src/github.com/batazor/hcfc/cmd/hcfc
DEBU[2019-04-03T11:22:05+03:00] go build -v main.go
```

**Comment by aaronhnatiw** [comment]
I'm having the same problem here as everyone above. The only way `packr2` will find the boxes is when I run it from the the `cmd/` subdirectory where my `main.go` file is. The only alternative I have is to run it in the project root directory with `--ignore-imports`.

**Comment by Gowee** [comment]
With `--ignore-imports`, packr2 finds the box.
But `go build` gives another error `pkg/assets/assets-packr.go:8:8: package .../packrd is not in GOROOT (.../packrd)` where `...` is the project root.

Although I am still not sure what the problem is and how it can be fixed properly, manully fixing `import _ ".../packrd"` in `pkg/assets/assets-packr.go` make it work well, according to https://github.com/gobuffalo/packr/issues/169#issuecomment-474205649.
