### ISSUE TITLE
packr2 generates import paths relative to go.mod, not the directory it was run in

### ISSUE THREAD

**Issue by kat-co** [gobuffalo/packr#178]
We are running `packr` in a sub-directory of our project, `foo`. A `foo-packr.go` file is generated which contains an import:

```go
import _ "my.project/root/packrd"
```

This is a mismatch with where the `packrd` folder is actually generated, `my.project/root/foo/packrd`.

**Comment by sagikazarmark** [comment]
I submitted a fix which I believe solves the problem (tested it and works for me), but I'm not sure the tests are perfect.

**Comment by kat-co** [comment]
Thank you, @sagikazarmark!
