### ISSUE TITLE
Looks like it's not working with go.mod

### ISSUE THREAD

**Issue by Daavidaviid** [gobuffalo/packr#181]
Hi,
I'm working on a go project, trying to deploy it on a server.
I'm using go.mod.
`go.sum` : 
```
github.com/gobuffalo/packr/v2 v2.0.8 h1:y9isj2HQn00A468xqeujViV9raJX5gRL3WLg811cgFE=
github.com/gobuffalo/packr/v2 v2.0.8/go.mod h1:vWcRwd/rWAJitjF2pOG4Y79tAEkxjDKwsq9vQyQjdqw=
```
`go.mod` : 
```
module api

...

github.com/gobuffalo/packr/v2 v2.0.8
```

I then launch the command to build (successfully) : 
```
env GOOS=linux GO111MODULE=on GOARCH=amd64 packr2 build -o myServer -tags release
```

Then when launching the binary on the server I get the following : 

```
panic: open /Users/MY_LOCAL_USERNAME/workspace/MY_LOCAL_PROJECT/api/migration: no such file or directory
```

I'm stuck on this, I did not expect that to happen..
Someone encountered the same issue ?
Thanks

**Comment by markbates** [comment]
There’s. It enough detail in this ticket to help. My I recommend you try with the -v flag to see what it thinks it finds for boxes.

This sort of issue is almost always in the way you’ve coded the app, particularly in where/how you’re asking for files. . I would recommend trying a basic app to confirm it works.

If you still can’t figure it out, please add a reproducible example so others can help you diagnose.

-----------
Mark Bates

**Comment by Daavidaviid** [comment]
Damn it's working with a simple project as you said..
I don't know where it might come from as I just migrated from GOPATH to go.mod and it worked perfectly before.

**Comment by Daavidaviid** [comment]
My bad, it was coming from another library (go-pg/migration)
