### ISSUE TITLE
Accessing files away from service directory

### ISSUE THREAD

**Issue by vadimpiven** [gobuffalo/packr#182]
I've found one rather strange thing - when trying to open a file from outside of the directory served,... it works! Even after `packr2 build` and `mv` to another directory program tries to find and open files by related path. The same time, `http.Dir` just throws an error at the same place. So I've considered such a behaviour as a bug (correct me if I'm wrong). Example program:
```
package main

import (
	"fmt"
	"github.com/gobuffalo/packr/v2"
	"net/http"
)

func main() {
	b := packr.New("static", "static")
	f1, err := b.Open("../main.go")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(f1)
	}

	d := http.Dir("static")
	f2, err := d.Open("../main.go")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(f2)
	}
}
```
and it's output:
```
package main

import (
	"fmt"
	"github.com/gobuffalo/packr/v2"
	"net/http"
)

func main() {
	b := packr.New("static", "static")
	f1, err := b.Open("../main.go")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(f1)
	}

	d := http.Dir("static")
	f2, err := d.Open("../main.go")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(f2)
	}
}

open static/main.go: no such file or directory
```

**Comment by matthijskooijman** [comment]
The output you're showing is not entirely clear. I see just a single print, rather than two? It does not really show the problem clearly.

**Comment by cdreier** [comment]
we just ran in a similar problem.

the output above prints the content of main.go first (!) , and after that the error message from http.Dir 

so you can access relative paths out of the packr box - a big problem if you use a box as http.Dir as it makes the whole server vulnerable to path traversal attacks (https://www.owasp.org/index.php/Path_Traversal)

**Comment by fasibio** [comment]
I have the same problem.
This issue has a high security impact. 
You can Load files outside your box. 
The example, given by  @vadimpiven shows in the output section the content of main.go. 
The difference between the method http.Dir => Open and packr.Box => Open is this line: 
```name = filepath.Base(b.Path) + filepath.FromSlash(path.Clean("/"+name))```
So i try to fix the issue but only works outside the build binary..
Here my understanding of the packr build logik was to low... 
Look here https://github.com/fasibio/packr/commit/d18df6abf037f7d3438fb6fdcd13db7f14909529
I hope you understand the Problem...
I think it is important path traversal security issue.
