### ISSUE TITLE
[packr2] HasDir() does not return true for a prefix segment of dir

### ISSUE THREAD

**Issue by davidovich** [gobuffalo/packr#185]
consider:

```
└── subdir
    ├── a
    │   └── a.txt
```

If we say `box.HasDir("subdir")` I would expect that this returns `true`. But it currently returns `false`. The current [implementation builds a map of directories](https://github.com/gobuffalo/packr/blob/master/v2/box.go#L131) but only at the deepest level, so if there are nested directories, we cannot assert that a root exists.

I have a PR fix and test prepared for this if there is interest.

**Comment by markbates** [comment]
PRs welcome. :)

-----------
Mark Bates
