### ISSUE TITLE
Question: `packr.Box` Safe for concurrent access?

### ISSUE THREAD

**Issue by alexsasharegan** [gobuffalo/packr#19]
I've tested concurrent box access with race detection and load testing, and the answer to this question seems to be yes.

Could you add a line in the docs regarding a box's safety for concurrent access? Or best practices for using boxes? Are they extremely cheap to make, or should they be passed around via pointers? I'm relatively new as a go dev, so this sort of info is very helpful. Thank you!

**Comment by markbates** [comment]
They are safe for concurrent access and they are very cheap to make, no need to pass around pointers at all. Feel free and ask questions anytime.
