### ISSUE TITLE
Packr with external module?

### ISSUE THREAD

**Issue by bobby-brennan** [gobuffalo/packr#193]
I have a module `A` which contains a static HTML page with some CSS/JS. I'd like to `import A` from a separate golang project (call it `B`), and be able to serve the same HTML/CSS/JS from `B`.

Currently this doesn't seem to work - is there something I'm missing?

**Comment by timraymond** [comment]
@bobby-brennan I wasn't able to replicate this... I created a `moduleA` repo here: https://github.com/timraymond/moduleA which is what I think you're trying to do. I was able to import this and read the contents of `templates` in `moduleA`.

Maybe I'm not following. Could you provide a small reproduction test case and the error that you're seeing to help debug this?

**Comment by bobby-brennan** [comment]
I think I've gotten this working in packr2 - will reopen if I run into the issue again.

Thanks!
