### ISSUE TITLE
[v1] Why does the virtualFile Read method loop over back to the start?

### ISSUE THREAD

**Issue by hasen-mtic** [gobuffalo/packr#194]
I noticed the following code in the packr code:

```go
// Read reads the next len(p) bytes from the virtualFile and
// rewind read offset to 0 when it met EOF.
func (f *virtualFile) Read(p []byte) (int, error) {
    i, err := f.Reader.Read(p)

    if i == 0 || err == io.EOF {
        f.Seek(0, io.SeekStart)
    }
    return i, err
}
```

We were having a weird problem when we feed a file returned from `box.Open` to the csv.Reader. If the last line of the csv does not end with a newline '\n' character, the reader gets stuck in an infinite loop. 

This is because the csv reader assumes that once it hits an EOF, the next read will return an EOF, so if while reading a line it hits EOF instead of '\n', it doesn't do any special handling.

But the `virtualFile` violates this assumption. Since the file rewinds back to position 0, the next csv read will read the first line again. This pattern keeps repeating forever.

What is the reason for rewinding back to start after hitting EOF?

I want to send a PR to "fix" this, but it seems like this was put there intentionally for a reason.

I have a work around which is to use Find instead of Open:

```go
var content, err = box.Find(filename)
// error checking snipped
var csvReader = csv.NewReader(bytes.NewReader(content))
// start using the reader
```

**Comment by markbates** [comment]
PRs for v1 aren’t being accepted any more. I don’t recall the origin of that code, but my gut says it allows the file to re-read. If it wasn’t there it can only be read once. Again, that’s a hot take on old code.

-----------
Mark Bates

**Comment by hasen-mtic** [comment]
Actually I just realized this issue is with `packd`

Is it possible to move the issue to the other repo? If not I will just make a new issue there.
