### ISSUE TITLE
Has & MustBytes don't have the same behavior

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/packr#20]
Trying to test for a file existence, using `box.Has(file)`.

Create a temp file:
``` go
f, err := ioutil.TempFile("", "test")
```

```go
box.Has(f.Name()) // KO
```

```go
box.MustBytes(f.Name()) // OK
```

**Comment by matthewljsmith** [comment]
I think I ran into a similar issue, stemming from the `Box.find` function, if there's no extension on the filename it returns the result of `newVirtualDir` instead which makes the return of `Has` true even when it feels like it shouldn't be, Maybe a more specific `HasFile` would make it more obvious as to the return value.
