### ISSUE TITLE
File server is not working from directory where it can locate directory in my file system

### ISSUE THREAD

**Issue by babu-bhaia** [gobuffalo/packr#202]
Here is the line of code from my application:
```
	FSBox := packr.New("fileServer", "./../../public")
        http.Handle(basepath+"/static/", http.StripPrefix(basepath+"/static/",http.FileServer(FSBox)))
```
Now when I execute command `application.exe` from my current directory. It found public directory on path  `./../../public`  and doesn't render the page in browser.
But if I do` cd ..` and then execute `bin\application.exe` it works just fine.
So basically it limits where I can execute my binary. If I execute from current directory if it found public directory at path `./../../public` it will just fail. 

**I am using packr 2.2.0**

**Comment by babu-bhaia** [comment]
@markbates please let me know if you want me to elaborate the issue further. I don't think this is an environment issue.

**Comment by markbates** [comment]
You haven't provided a reproducible project, so as far as I can tell it's environmental. You're also access stuff WAY outside of where packr expects things to be. If you're using `../../` that's usually a good indicator that things aren't in the correct place.

So, until you can provide a fully reproducible example case, it looks environmental.

**Comment by babu-bhaia** [comment]
My issue is similar to this one `https://github.com/gobuffalo/packr/issues/198`.

**Comment by markbates** [comment]
Dup of #198
