### ISSUE TITLE
prospects with `_` prefix in any part of path are ignored

### ISSUE THREAD

**Issue by omerkay** [gobuffalo/packr#210]
Not sure if this is a bug or intended behavior.

packr2 seems to ignore prospects residing under paths with `_` prefix in any part.
I have noticed this might have been introduced with this change: https://github.com/gobuffalo/packr/pull/112/files

This conflicts with Jenkins behavior (which I would also consider a bug):
https://issues.jenkins-ci.org/browse/JENKINS-38706
**tl;dr** 
Jenkins assigns a workspace path for a build, including trimming of long parts, which may result in unexpected prefixes inside the path (in this case, `_`).

----------------------------------------------------------------------------

If anyone is struggling with this as well, we are currently using a workaround on Jenkins side, using custom workspace in our pipeline, which solves this issue.

**Comment by markbates** [comment]
In Go any folder starting with an underscore is not considered to be buildable code, which is why it’s ignored. It keeps packr consistent with expected Go behavior.

**Comment by omerkay** [comment]
@markbates yes, but what if your Go project resides under path with underscore prefix?
i.e. `/var/lib/jenkins/workspace/_im_not_a_go_project_root/<GO_PROJECT_ROOT>`
it seems `packr2` takes all absolute path parts into consideration.

**Comment by markbates** [comment]
Yes, because that’s considered un buildable code. It’s intended behavior.

**Comment by markbates** [comment]
All of packr is easily called programmatically so you can write a script that does just what you need it do.

**Comment by omerkay** [comment]
seems odd that path parts outside of the project scope are being considered and making the whole project "unbuildable".
this is definitely not the case for `go build`.

**Comment by markbates** [comment]
Sorry.

**Comment by omerkay** [comment]
no worries, just wanted to bring this up since it was unexpected for us to encounter.
thanks for the great work with this project!

**Comment by markbates** [comment]
If you can come up with a PR that solves the issues and keeps in line with Go, go for it. It’s a level of effort though, and one I don’t have the time to put in, hence the global ignoring of _
