### ISSUE TITLE
Using packr inside a plugin

### ISSUE THREAD

**Issue by pagameba** [gobuffalo/packr#216]
I'm trying to build a plugin that uses packr v2 to bundle a couple of images and having some trouble figuring out path issues.  I've looked through related issues and still can't figure out the correct solution (if indeed what I'm trying is possible).  

There are two projects. The main project is https://github.com/canvaspop/thumgor which is an image server designed to run as a cli, web server and AWS lambda function. One of the features I'm trying to build into thumgor is the ability to load plugins so its functionality can be extended.  I have a second library that is private that is built as  a plugin for the first. The directory structure looks like

```
├── README.md
├── assets
│   ├── pillow-1-shadow.png
│   └── pillow-1.png
├── framed.go
├── go.mod
├── go.sum
├── pillow.go
├── product.go
├── single.go
└── triptych.go
```

The `assets` are referenced inside `pillow.go` as follows:

```
box := packr.New("Assets", "./assets")
imgBytes, err := box.Find("pillow-1.png")
fmt.Println("### box.List() ->", box.List())
```

To build the plugin, I run the following inside the `thumgor` folder (

    packr2 build -buildmode=plugin -o plugins/product.so github.com/canvaspop/thumgor-plugins/

To run `thumgor` locally, I would run:

    go run cli/cli.go --url "/unsafe/fit-in/256x256/filters:format(png),product(PI,1)/https://images.unsplash.com/photo-1507146426996-ef05306b995a" out.png

which works and the log will report

    ### box.List() -> [pillow-1-shadow.png pillow-1.png]

When I bundle this as a lambda for AWS, I have to build inside a docker container because I can't cross compile on MacOS and plugins require the cross compile option, so I have a script `bin/build.sh` that looks like this:

```
cwd=`pwd`
cd /tmp

git clone https://github.com/canvaspop/thumgor.git
cd thumgor

GOOS=linux GOARCH=amd64 go build -v -o "$cwd/thumgor" cli/cli.go
cp config.yml "$cwd/config.yml"

go get -u github.com/gobuffalo/packr/v2/packr2
GOOS=linux GOARCH=amd64 packr2 build -v -o "$cwd/plugins/product.so" -buildmode=plugin github.com/canvaspop/thumgor-plugins/
``` 

which is run inside docker using a command like this:

`docker run --rm -it -v ~/.netrc:/root/.netrc -v "${PWD}":/usr/src/myapp -w /usr/src/myapp golang:1.12.6 bin/build.sh`

When I trigger the lambda, it does not work and I get the following:

```
### box.List() -> []
stat /var/task/assets/pillow-1.png: no such file or directory: PathError
```

The actual paths inside the lambda, as I understand it, are

    /var/task/thumgor # the executable
    /var/task/plugin/product.so # the plugin

**Comment by markbates** [comment]
https://github.com/gobuffalo/packr/blob/master/v2/packr2/cmd/install.go

Build and install have been deprecated and shouldn’t be used. Also plugins aren’t considered “production” ready. Lots of bugs, limited platforms, etc... you didn’t ask for it, but my advice would be to figure out a different way. $.02.

**Comment by pagameba** [comment]
ok thanks, there are definitely other ways I can go with this - I just really liked Packr :)  Maybe I'll find another use for it later.
