### ISSUE TITLE
Working with Package directories

### ISSUE THREAD

**Issue by shawnbutts** [gobuffalo/packr#22]
I have a project structure like this:
├── main.go
└── package
│   └── mypackage.go
└── templates
    ├── admin
    │   └── index.html
    └── index.html

When I run go run or go build from main.so directory, everything works as expected. the mypackage.go contains a line like box := packr.NewBox("./templates/")
However, when i run packr build in the same directoy I get the following error.

Error: could not find folder for box: /package/templates

How can I get this working?

Thank you

**Comment by markbates** [comment]
Use ./package instead of /package. The first is relative the second is absolute path.

**Comment by shawnbutts** [comment]
Where?

I'm using packr.NewBox("./templates/") as ./templates/ is correct relative to to the main.go.

packr seems to be looking for something relative to ./package/.  Which is not what I expect.

**Comment by markbates** [comment]
Paths are relative to where the NewBox is declared. So for example if you use NewBox in the package directory to use the templates folder it would be ../templates. Does that help?

-----------
Mark Bates

**Comment by shawnbutts** [comment]
That works. 

Thanks for the prompt response.
