### ISSUE TITLE
Errors related to envy when I compile myself?

### ISSUE THREAD

**Issue by carolynvs** [gobuffalo/packr#237]
After updating to release 2.6.0 I started getting errors about envy suddenly. I'm not sure if I am missing a step, or if there was a regression?

```
$ packr2 version
[ENVY] unable to load env file(s) on init: open .env: no such file or directory
```

```
$ packr2 clean
bash: [ENVY]: command not found
```

I just went back to 2.5.3 and verified that these commands execute without error.

Update:
It must be something with how I'm building / my development environment. If I download the binaries, they don't have this problem. But if I build them myself, then they all have this issue, regardless of version. So perhaps this is just me, sorry! If you think it's me, feel free to just close and I'll figure something out.

**Comment by markbates** [comment]
@carolynvs someone upstream committed a warning message, it got reverted, so you should be good now.
