### ISSUE TITLE
Apache License in packr/main.go?

### ISSUE THREAD

**Issue by eclipseo** [gobuffalo/packr#239]
The license for the package is MIT but the header of https://github.com/gobuffalo/packr/blob/master/packr/main.go contains Apache 2.0. Is it an error or is it dual licensed?

Thanks.

**Comment by markbates** [comment]
An error. All gobuffalo organization licenses are MIT. 

--
Mark Bates

**Comment by eclipseo** [comment]
Ok thanks!

**Comment by QuLogic** [comment]
Maybe should leave this open until the header is fixed, or it might get forgotten.
