### ISSUE TITLE
creating a packr/v2 box loads .env files

### ISSUE THREAD

**Issue by wayneashleyberry** [gobuffalo/packr#245]
packr depends on envy, envy loads `.env` files in an `init()` function. I'd consider this a side-effect and don't think it should happen automatically. This means that by simply importing `packr.New` any `.env` files will be automatically processed.

For my use case, we only ever load `.env` files during local development, and do so explicitly using the `godotenv` command — but now we have no control over that because any package that depends on `packr.Box` will load `.env` files.

- [gobuffalo/envy#init](https://github.com/gobuffalo/envy/blob/909ea676d4c90832fefbf55a5a4fb04d8bef8931/envy.go#L35-L38)
- [test repo](https://github.com/wayneashleyberry/packr-issue245)
- [build output](https://github.com/wayneashleyberry/packr-issue245/commit/6a293bb4acf1cc25359afedc361892d781111f52/checks?check_suite_id=261515536#step:5:6)

**Comment by wayneashleyberry** [comment]
I'm going to close this until I can create a clear repro.

**Comment by stanislas-m** [comment]
Fixed with #257.
