### ISSUE TITLE
Publish binaries for releases

### ISSUE THREAD

**Issue by metalmatze** [gobuffalo/packr#25]
Hey! 
I really enjoy packr and use it on over 10+ projects now. During my CI/CD I sometimes need to `go get` packr, which is rather annoying because it takes a minute. It would be super dope, if you could provide some pre-build binaries (linux-amd64 for me). That way I could just curl them in my CI/CD and that's it. 
Thanks!

**Comment by markbates** [comment]
That would be great. A PR would be awesome.

**Comment by metalmatze** [comment]
How would I do a PR so you can upload the binaries? Are you talking about Travis? 🤔

**Comment by markbates** [comment]
Yeah, I’m not quite sure how to go about it. My guess would be that we would use travis to build binaries and then push those to GitHub somehow.

-----------
Mark Bates

**Comment by metalmatze** [comment]
Yep. I do that with drone a lot. I'll just have to take a look on how to do it with Travis when tagging. 😎

**Comment by markbates** [comment]
You are awesome!

**Comment by markbates** [comment]
The command "GOARCH=amd64 GOOS=darwin go build -v -o packr_darwin_amd64 ./packr" exited with 0.
Skipping a deployment with the releases provider because a custom condition was not met

**Comment by metalmatze** [comment]
Yes. The condition is, that it is only run iff a release was tagged with `git tag`

**Comment by markbates** [comment]
Not working. :(

https://travis-ci.org/gobuffalo/packr/jobs/312706654

I tagged that on using `git tag v1.9.3` and then did `git push origin --tags`. Travis picked it up, built them, but didn't deploy them. Thoughts?

**Comment by metalmatze** [comment]
It might be this line which prevents the build from running that step. 
But we need that due to the matrix of running the builds with different Go versions. We only want to push the binaries built with Go 1.9.

https://github.com/gobuffalo/packr/blob/782425e1c1b9582847237f22d83d16cb6908a047/.travis.yml#L29
