### ISSUE TITLE
This broke our CI pipeline for several projects :'(

### ISSUE THREAD

**Issue by sio4** [gobuffalo/packr#296]
Hi @JDiPierro,

I read your following comment on the PR for packr/v2. Could you please add some more information or symptom of the issue + a brief description of your use case + your environment?

--- the original comment ---
This broke our CI pipeline for several projects :'(

The installation methods in the README need to be updated.
```
$ go get -u github.com/gobuffalo/packr/v2/packr2
```
this no longer works.

_Originally posted by @JDiPierro in https://github.com/gobuffalo/packr/issues/295#issuecomment-974307949_

**Comment by chuijh** [comment]
We had the same issue and ended up removing the v2 from the path

**Comment by sio4** [comment]
I see. If you are able to install `packr2` by running the command as follows, it must be an issue of the go version. By version 1.16 of go, which is our minimum supported version, the behavior of `go get` changed to enable GO111MODULE=on by default, and the package argument resolution automatically translates version part of the package (`v2` of `.../packr/v2`) argument. If it was just treated as a path on the source tree, it seems like you are using GOPATH mode in your environment.

Will update the doc accordingly.

```
go get -u github.com/gobuffalo/packr/packr2
```
