### ISSUE TITLE
Master branch issue with v2 references

### ISSUE THREAD

**Issue by rgcooper53** [gobuffalo/packr#298]
Please explain, maybe I'm missing something. Your master branch no longer has a packr/v2 directory and your commit comments confirm that, yet every source file I look at imports packr/v2 package paths. We are referencing go get ..packr@v2.8.3 as a workaround, without that our builds fail. 

Thanks.

**Comment by sio4** [comment]
Yes, that is true. Currently, the `master` branch only contains v2 of packr so in source-level the `/` is actually the same as the content of the previous path `/v2`. However, if you turn `GO11MODULE` on, the default mode for golang 1.16 which is the oldest supported version by packages of buffalo family, the import path is still valid for the v2 of `packr` so I guess your environment is still in the old `GOPATH` mode.

Are you using `packr/v2` for the buffalo app or something else?

If you are using please consider updating buffalo to 0.18 which is the latest version, which is already migrated to `go:embed` from `packr`. From now on, buffalo does not use `packr` anymore and the support for `packr` will not be continued. 

If you use `packr` for the other application and your go version supports go module, please consider turning the environment as GO11MODULE on.
