### ISSUE TITLE
Add support for `-i` flag

### ISSUE THREAD

**Issue by markbates** [gobuffalo/packr#41]
See ticket #38 

When running `packr` as a replacement for the `go` tool it doesn't work correctly with the `-i` flag.

**Comment by Michael-Dixey** [comment]
@markbates 
Is there support for running packr as a replacement for the go tool in Windows?  If so, where is default directory of the packr.exe? I can't seem to find it.

**Comment by markbates** [comment]
When Go installs binaries they are all placed into GOPATH/bin. Assuming the install was correct, you should see it there.

-----------
Mark Bates

**Comment by Michael-Dixey** [comment]
I realized I only installed via "go get github.com/gobuffalo/packr",   after running the "/packr/..." , the binary appeared.  Thanks.
