### ISSUE TITLE
go generate?

### ISSUE THREAD

**Issue by tj** [gobuffalo/packr#48]
Looks like a nice replacement for go-bindata! But it seems to not allow you to use it with go:generate, unless that wasn't the intent. It'd be awesome to just drop `// go:generate packr` in there.

go-bindata had a few weird defaults so you always have to specify flags, I usually end up doing this if checked into source:

```
//go:generate go-bindata -ignore bindata.go -modtime 0 -pkg NAME .
```

or I guess just:

```
//go:generate go-bindata -ignore bindata.go -pkg NAME .
```

if it's not checked into GIT, but I think the CWD and name could be inferred easily and would be a nicer experience

cheers!

**Comment by markbates** [comment]
```
//go:generate packr2 -v

package main

import (
	"net/http"

	"github.com/gobuffalo/packr/v2"
)

func main() {
	box := packr.New("my box", "./templates")
	http.Handle("/", http.FileServer(box))

	http.ListenAndServe(":3000", nil)

}
```

This definitely works in v2. Closing this, please re-open if it's still an issue. Thanks.
