### ISSUE TITLE
sql-migrate now supports (and recommends) packr

### ISSUE THREAD

**Issue by rubenv** [gobuffalo/packr#49]
Not a real issue, just wanted to announce that [sql-migrate](https://github.com/rubenv/sql-migrate) now supports packr. I'm liking it so much that I'm making it the recommended way of embedding SQL migrations.

Trivial implementation as well, thanks to the neat and clean packr interface: https://github.com/rubenv/sql-migrate/commit/10fe3dd0bdb246fe4d2d15a3c4dd6a4475293734

Feel free to close, just wanted to say thanks for this awesome library!

**Comment by markbates** [comment]
Thanks for letting us know. That’s really nice to hear! 😊
