### ISSUE TITLE
Support for prefix of embedded files

### ISSUE THREAD

**Issue by danielfrg** [gobuffalo/packr#53]
I am trying to move from `go-bindata` since its unsupported, that project has a flag in the CLI that allows you to add a prefix to all the files that are embedded so you can do something like this:

```go
router.Handler("GET", "/static/*filepath", fileServer)
```

Right now this works:

```go
staticBox := packr.NewBox("../dist")
fileServer := http.FileServer(staticBox)
router.Handler("GET", "/*filepath", fileServer)
```

But I have to serve from `/` and I have other routes there.

The following doesn't work because it will look for a file under `../dist/static/app.js` the file that exists is `../dist/app.js`.

```
staticBox := packr.NewBox("../dist")
fileServer := http.FileServer(staticBox)
router.Handler("GET", "/static/*filepath", fileServer)
```

What I want is something like:

```
staticBox := packr.NewBox("../dist", "static")
fileServer := http.FileServer(staticBox)
router.Handler("GET", "/static/*filepath", fileServer)
```

Maybe this is something already exists that I could not find or maybe you can point me how to write a small function that changes the routes of the embedded files inside a box, not a go expert :)

**Comment by markbates** [comment]
I think what you're looking for is:

https://golang.org/pkg/net/http/#example_FileServer_stripPrefix

**Comment by danielfrg** [comment]
Exactly what I was looking for. Thank you so much!
