### ISSUE TITLE
Having invalid (but unused) go files anywhere in the project path fails packr build

### ISSUE THREAD

**Issue by fletcher89** [gobuffalo/packr#56]
Trying to use the `packr build` command in a project that has invalid (but unused) go files fails the command.

I'm using JetBrains File Templates to create some boilerplate code in my project. Those involve creating and storing invalid go files within my project structure (inside the .idea project directory).

Now, when I execute `packr build` in the project root I get the following output:

```bash
$ packr build
Error: /Users/fletcher/go/src/project/.idea/fileTemplates/file_template_1.go:1:1: illegal character U+0023 '#'
Usage:
  packr build [flags]

Flags:
  -h, --help   help for build
```

Note: `go build` works just fine

**Comment by fletcher89** [comment]
I guess the obvious solution would be to include .idea into the list of directories skipped by builder.Builder's Run() method.

**Comment by markbates** [comment]
A PR would be excellent!

**Comment by fletcher89** [comment]
Sure, I've submitted the PR. Thanks!

**Comment by UlisseMini** [comment]
I have this issue with my [templating program](https://github.com/UlisseMini/gocs), i have templates that are invalid go code and so it refuses to build

for example

```go
// Copyright {{.Year}} {{.Author}}. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package {{.Project}}
```

I could work around this by naming them something like `.goo` and having my program change the names, but i'd rather this was fixed

**Comment by markbates** [comment]
It’s idiomatic for template files to end in .tmpl might I recommend you follow that convention.

-----------
Mark Bates

**Comment by UlisseMini** [comment]
@markbates Maybe i'll do that, seems like a overhead when creating templates since you would need to name them `foo.go.tmpl` and that is kind of busywork

**Comment by markbates** [comment]
That’s the idiomatic go way of writing templates. You can also put them in a folder starting with an _ Go won’t build any files in a directory starting with _

-----------
Mark Bates

**Comment by UlisseMini** [comment]
You misunderstand me, `go build` works fine `packr build` throws this error
```
➜  gocs git:(master) ✗ packr build
Error: go/src/github.com/UlisseMini/gocs/goc_default/templates/default/{{Project}}.go:5:9: expected 'IDENT', found '{'
Usage:
  packr build [flags]

Flags:
  -h, --help   help for build

Global Flags:
  -v, --verbose   print verbose logging information

```
I don't see why packr needs to scan all `.go` files including in subdirectories and make sure they are syntastically valid.

**Comment by markbates** [comment]
I don’t misunderstand you, I’m just explaining how things work. Packr follows Go rules.

-----------
Mark Bates

**Comment by UlisseMini** [comment]
If `packr` follows go rules, why does `packr build` fail when `go build` is fine?

**Comment by UlisseMini** [comment]
I've fixed it by changing `templates` to `_templates`, thanks for the help :)

**Comment by markbates** [comment]
Just to clarify what's happening. Packr scans your .go files looking for boxes, using go/package. Because those files aren't "proper" go files, the Go tools to parse the package error out. You need to tell Packr to skip those when parsing, to do that it follows the same conventions Go does when trying to figure out what it should/shouldn't build.

**Comment by UlisseMini** [comment]
Thanks for explaining, it makes sense now :)
