### ISSUE TITLE
Packr silently fails when project built by Jenkins 

### ISSUE THREAD

**Issue by olofwalker** [gobuffalo/packr#57]
We have a very hard to solve issue that involves packr, when run on our local workstations (Fedora and MacOS) the packr build command generates a correct executable containing all the files in the packr box. 

However, when built on Jenkins (using a Alpine image), the resulting executable contains no files. 

Its very perplexing issue, Jenkins just clones the same repository that we are using, running the same commands, but the result ends up differently and we cannot see any error messages in the log from packr.

Any suggestion where we can start looking ?

**Comment by markbates** [comment]
Try this new release https://github.com/gobuffalo/packr/releases/tag/v1.10.9 it properly supports the `-v` flag. Try turning that on and it will print off what boxes it's building and what files it's packing, along with the `go build -v` information. Hopefully that will help.

**Comment by olofwalker** [comment]
The only thing it prints is the fully qualified package name, I even removed the directory referenced by when creating a new box, nothing.

**Comment by markbates** [comment]
I don’t know Jenkins, so I can’t speak to what is happening there. 

But are the files you expect to be packed there? Are you in the right directory? I’m at a loss. There’s something that’s missing, but without knowing Jenkins and your app, it’s hard to say. 

Packr works by looking at the source files for NewBox declarations and then following those paths and packing files. So if there’s nothing in those paths, then nothing would get packed. 

Again, I don’t know Jenkins or the app, so it’s hard to say.

**Comment by markbates** [comment]
This should be fixed in v2. Closing this issue for now. Please re-open if the problem still persists with v2.
