### ISSUE TITLE
confusion over how packr finds folders for boxes

### ISSUE THREAD

**Issue by pharrisee** [gobuffalo/packr#62]
Strange title I know, but...

I'm writing a small web framework which is going to be very opinionated.  It mandates that templates must be in a folder called 'views' and that static files are in a folder called 'static'.  I would like to be able to use packr to package the files for delivery.

I wanted to create the packr.Box within the framework but it seems that by doing that packr looks in the folder of the framework, rather than the folder of the main application, for the 'boxed' files.  If I create the packr.Box within the main app and pass that to the framework all works as expected.

Am I going slightly mad? or is what I describe above actually happening?

**Comment by HazCod** [comment]
Try with `../`

**Comment by markbates** [comment]
Dup of #162
