### ISSUE TITLE
Support exclude/include file during packing

### ISSUE THREAD

**Issue by leaanthony** [gobuffalo/packr#63]
Problem: It is only possible to pack entire directories. There are situations when it would be good to exclude certain files from boxes.

**Comment by ghostsquad** [comment]
Yes please. I found this repo, and immediately looked for that functionality.

**Comment by ghostsquad** [comment]
Ideally, I should be able to pack just a simple list of files.

**Comment by markbates** [comment]
Programmatic box access, custom resolvers, custom stores, etc... fix this. 

I’m closing as this won’t be back ported to v1. 

Please try the v2 betas for this new functionality.

**Comment by ghostsquad** [comment]
@markbates where can I find the v2 betas?

**Comment by markbates** [comment]
https://github.com/gobuffalo/packr/releases
