### ISSUE TITLE
Build errors on Alpine Linux

### ISSUE THREAD

**Issue by andrewmeissner** [gobuffalo/packr#64]
I'm trying to get packr working on alpine linux in a docker container.

After I `wget` it from the releases page, I put it in my `PATH`.

When running `packer build -v app .`, I get this error:

```bash
/go/bin/packr: line 1: S��8���: not found
: not foundkr: line 1: ���
/go/bin/packr: line 2: z�L���Ap�M: not found
/go/bin/packr: line 2: syntax error: unexpected word (expecting ")")
```

In alpine, before I run packr I'm running `apk add --update --no-cache alpine-sdk linux-headers wget`... am I missing any other packages?  Should I not be building on alpine?

**Comment by markbates** [comment]
Closing as this issue is very old, and can't be reproduced.
