### ISSUE TITLE
How to build the packr binary?

### ISSUE THREAD

**Issue by steveww** [gobuffalo/packr#73]
I have packr working with my go program running directly from the filesystem. It's cool. Want to package those files into the binary and I need the packr command to do that but I can't figure out how to build it. 

It would be great to add these instructions to the README.

**Comment by markbates** [comment]
installation instructions are in the readme

go get github.com/gobuffalo/packr/packr

**Comment by steveww** [comment]
So I'm new to go.

go get GitHub.com/gobuffalo/packr
cd src/github.com/gobuffalo/packr
go build

Nothing happens.

**Comment by markbates** [comment]
And for its worth, the instructions in the README will install download, compile, and install the binary in GOPATH/bin.

**Comment by markbates** [comment]
Ah. Ok. That just builds the package. Try go install -v ./packr to install the binary from source. Sorry, I thought you were looking to install from GitHub.

--
Mark Bates

**Comment by steveww** [comment]
I installed via dep

$ dep ensure

That does not build the packr binary for you. You need to the whole thing again in a different GOPATH to get the binary built.

Go it built now. Thanks.
