### ISSUE TITLE
Use `github.com/karrick/godirwalk` instead of `filepath.Walk`

### ISSUE THREAD

**Issue by kteb** [gobuffalo/packr#81]
I came across this library today, it started as a part of dep and became it's own library. I really liked the way it created abstraction for the path between Windows and Unix style paths (from the Readme):

> In other words, even on Windows, `filepath.Walk` will invoke the
callback with `some/path/to/foo.txt`, requiring well written clients
to perform pathname normalization for every file prior to working with
the specified file. In truth, many clients developed on unix and not
tested on Windows neglect this subtlety, and will result in software
bugs when running on Windows. This library would invoke the callback
function with `some\path\to\foo.txt` for the same file when running on
Windows, eliminating the need to normalize the pathname by the client,
and lessen the likelyhood that a client will work on unix but not on
Windows.

If it can avoid us problems between the paths, it could be nice.

**Comment by markbates** [comment]
used in v2
