### ISSUE TITLE
conflict/override problem  when same box name & path inside different module   

### ISSUE THREAD

**Issue by ftao** [gobuffalo/packr#82]
```
├── main.go
└── module_a
     └── model
└── module_b
     └──model
```

both module_a & module_b have some code like following . 
```
modelBox := packr.NewBox("./model")
modelBytes := modelBox.MustBytes("model.pb")
```
It works in development mode . (go build )
But when using packr build , `modelBytes`  become same in different module .. 
Because the box name & path is identical , the generated code in one module will override another ..

**Comment by markbates** [comment]
This should be fixed in v2. Closing this issue for now. Please re-open if the problem still persists with v2.
