### ISSUE TITLE
Box.Has does not work correctly for directories

### ISSUE THREAD

**Issue by bastiankoetsier** [gobuffalo/packr#86]
Having this conditional https://github.com/gobuffalo/packr/blob/master/box.go#L135 before this one https://github.com/gobuffalo/packr/blob/master/box.go#L140 prevents `Box.Has` to correctly respond `true` for directories. Would you mind a PR that changes that behaviour?
Thank you for your work @markbates  !

**Comment by markbates** [comment]
Please! PR-away. :)
