### ISSUE TITLE
Improve and standardize Must* convention

### ISSUE THREAD

**Issue by rasky** [gobuffalo/packr#96]
In Go's standard library, `Must*` functions are meant to skip error checking converting any error in a panic.

Just to give two examples:

 * `func regexp.Compile(expr string) (*Regexp, error)`: compile a regular expression, and returns an error if the syntax is not valid.
 * `func regexp.MustCompile(str string) *Regexp`: compile a regular expression, and panic if the syntax is not valid.
 * `func syscall.LoadDLL(name string) (*DLL, error)`: load a dynamic link library, and return an error if it doesn't exist or is invalid.
 * `func syscall.MustLoadDLL(name string) *DLL`: load a dynamic link library, and panic on any error.

In `text/template`, there is also a `template.Must` which wraps any call the returns a `(*Template, error)` and panics if the error is not `nil`, so that you can do `var t = template.Must(template.New("name").Parse("html"))`, that is leverage chaining for situations where you know that there cannot be an error.

In all the above cases, the `Must` function is useful because there are situations in which the function cannot possibly fail at runtime unless it's a programming error; for instance, if you compile a regular expression which is statically defined in the source code, it either always fails or doesn't; using `MustCompile` is a nice shortcut to get a development-friendly panic while developing, and not bothering with explicit error checking for something that cannot fail. In the other example, `MustLoadDLL("system32.dll")` can't obviously fail on any Windows system.

packr seems to diverge from this pattern. For instance:

 * `func (b Box) MustString(name string) (string, error)`  returns the string type and an error
 * `func (b Box) String(name string) string` returns an empty string, **silently ignoring** (!) the error

This API is unexpected to Go programmers as it uses the `Must` convention in what *looks* like a reverse pattern compared to the standard one, but it's actually dangerously different: the function that does not return the error in fact silently ignores it, rather than panicking.

While writing code, I had used `box.String("foo")` hoping to get a panic in case the file did not exist. Instead, I managed to deploy code that had mistakenly run `go build` instead of `packr build` and the program did not panic but rather propagated an empty string with bad consequences. In Go, all errors are always explicitly checked; silencing an error requires an explicit `foo, _ := something()` pattern that is immediately visible as dangerous.

I propose to change to fix this by changing the semantic of all box functions to match the standard pattern:

 * `func (b Box) String(name string) (string, error)`: returns the string type and an error
 * `func (b Box) MustString(name string) string`: returns the string type and **panics** in case of error

Those who want to silently ignore the error can do so with `data, _ := mybox.String("foo")` but this should be the exception rather than the rule.

I understand this is a breaking change and probably requires a major version bump `go.mod`. I don't see a different solution given the current status of the API, but maybe there are alternative options to fix this that I cannot think of.

**Comment by markbates** [comment]
It would be a breaking change and a major version.

However this has been brought up before and my position is that panics are bad and shouldn’t be used.

I know there is precedent in the standard library for this pattern; but I’m also aware that this pattern has been frowned upon by the Go team in the years since it was introduced.

Packr will not be following that convention.

Thanks.

-----------
Mark Bates

**Comment by rasky** [comment]
@markbates I elaborated on why I feel panics are appropriate in the context of specific `Must` functions that cannot fail at runtime. packr seems to follow this pattern as far as I can tell, because if a file has been correctly packed (no programming error), there's no way that it's loading can fail at runtime. I'm sorry to hear that you don't feel that convincing, as I can't see how a panic that never happens can be a problem.

Would you please consider at least changing name convention to avoid confusing users? I reported a real mistake happened in real code because of the non-conforming usage of the pattern. Changing name to the functions would help.

**Comment by markbates** [comment]
Please don't get me wrong; I very much appreciate your argument and points. You've done a better job of selling it than the others in the past, but the use of `panic` is a hill I'm willing to die on. :)

With that said I have a `v2` PR open, https://github.com/gobuffalo/packr/pull/94, I would be willing to deprecate the `MustX` methods in favor of `GetXE` methods.

**Comment by rasky** [comment]
That’s fine, as long as `Must` is not used, any name would do it.

What is the rationale for ever providing methods that ignore the error? I can’t think how they are supposed to help without causing potential harm, but I’m surely missing something
